export const UI_TEXT = {
  appTitle: "ISAAC App",
  homeTitle: "ISAAC Reddit Sampler",
  homeSubtitle:
    "Select a social group and time period to retrieve a random sample of Reddit posts in ZIP format.",
  socialGroupLabel: "Social Group",
  socialGroupHelper: "Select a social group to sample posts from.",
  numDocsLabel: "Number of Documents (Optional)",
  retrieve: "Retrieve",
  retrieving: "Retrieving...",
  stop: "Stop",
  currentStage: "\u23F3 Current Stage",
  downloadZip: "Click to Download ZIP",
  issueTitle: "Report an Issue",
  issueSubtitle:
    "If you notice any bugs, inconsistencies, or have feature suggestions, please describe them below. Your email will be used to follow up if needed.",
  issueDescLabel: "Issue Description",
  issueSend: "Send",
  issueSending: "Sending...",
  snackbar: {
    invalidFields: "Please provide valid input fields.",
    noFiles: "No files found for the selected range.",
    fileReady: "File ready for download!",
    stopped: "Sampling stopped by user.",
    progressFailed: "Progress check failed.",
    sampleFailed: "Sampling failed",
    issueEmpty: "Please describe the issue.",
    issueSuccess: "Issue submitted successfully!",
    issueError: "Failed to send issue report.",
  },
  auth: {
    welcomeTitle: "Welcome to ISAAC",
    welcomeText:
      "ISAAC lets you sample Reddit posts by social group and period. Secure login keeps your preferences safe.",
    copyright: "\u00A9 2025 ISAAC Research Platform",
    loginTitle: "Login to Your ISAAC Account",
    signupTitle: "Create a New Account",
    email: "Email address",
    password: "Password",
    login: "Login",
    signup: "Sign Up",
    forgotPassword: "Forgot Password?",
    resetSent: "Reset link sent. Check your inbox.",
    resetError: "Failed to verify reset session.",
    updatePassword: "Update Password",
    updateSuccess: "Password updated successfully.",
    passwordMismatch: "Passwords do not match.",
    resetInvalid: "Reset link is invalid or has expired.",
  },
};
